### ISSUE TITLE
appspot does not update slide when git repo updated

### ISSUE THREAD

**Issue by saurabh-hirani** [garyburd/talksapp#13]
Hi,

http://go-talks.appspot.com/ is a great way to host slides on github - but when I update my slide - it does not reflect in go-talks.appspot.com - the only way to view it is to rename my slide file. I cannot keep on renaming the slide file everytime I refresh it. Is there some caching interval after  which it tries to reload the github file / or once a slide url is hit - the only way to update it is to rename it??

**Comment by garyburd** [comment]
The presentation is cached for one hour.

Run the present tool locally to view the presentation while you are editing it.

**Comment by saurabh-hirani** [comment]
Oh ok - cool. Thanks for the prompt response. Keep up the great work! go-talks.appspot.com is awesome!
