### ISSUE TITLE
Outside packages

### ISSUE THREAD

**Issue by btracey** [garyburd/talksapp#15]
Does each talk get a local GOPATH? I gave a talk that uses non-standard library packages. Can I vendor them into the talk directory and have it work?

My specific example is http://go-talks.appspot.com/github.com/gonum/talks/2015/intro_concurrency.slide#21

**Comment by garyburd** [comment]
> Does each talk get a local GOPATH?

No

> I gave a talk that uses non-standard library packages. Can I vendor them into the talk directory and have it work?

It will not work. The service uses play.golang.org to run code.  Play.golang.org does not run third-party packages.
